# Generated by Django 5.2 on 2025-06-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_position',
            field=models.CharField(choices=[('default', 'Default'), ('top', 'Top')], default='default', help_text='Позиція картинки (object-position)', max_length=10),
        ),
    ]
