# Generated by Django 5.2 on 2025-06-04 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_product_image_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_position',
        ),
    ]
