# Generated by Django 5.2 on 2025-06-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_product_image_url_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorprod',
            name='image_url',
            field=models.URLField(blank=True, help_text='Посилання на зображення (альтернатива завантаженню)', null=True),
        ),
        migrations.AlterField(
            model_name='favorprod',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/', verbose_name='Product image'),
        ),
    ]
