# Generated by Django 5.2 on 2025-06-17 15:20

import django.db.models.deletion
import myapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_favorprod_my_field_favorprod_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(default=myapp.models.generate_order_number, max_length=12, unique=True)),
                ('delivery_method', models.CharField(choices=[('courier', 'Courier'), ('post', 'Post')], max_length=10)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for'), ('published', 'Published')], default='waiting', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='orders/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
