# Generated by Django 5.2 on 2025-06-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_image',
        ),
        migrations.AddField(
            model_name='order',
            name='image_url',
            field=models.URLField(blank=True, help_text='Посилання на головне зображення (альтернатива завантаженню файлу)', null=True),
        ),
    ]
