# Generated by Django 5.2 on 2025-06-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_order_product_image_order_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='image_url',
        ),
        migrations.AddField(
            model_name='order',
            name='product_image_url',
            field=models.URLField(blank=True, help_text='URL зображення товару', null=True),
        ),
    ]
